# -*- coding: latin-1 -*-
# ---------------------------------------------------------------------------
# Licensed Materials - Property of IBM
# 5725-A06 5725-A29 5724-Y48 5724-Y49 5724-Y54 5724-Y55 5655-Y21
# Copyright IBM Corporation 2013, 2026. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with
# IBM Corp.
# ---------------------------------------------------------------------------
"""
Generic tests for Python API interfaces.

No command line arguments are required.
"""
import unittest
from cplex.exceptions import (CplexError, CplexSolverError,
                              WrongNumberOfArgumentsError)
from cplex.exceptions import error_codes


# This function comes from the following URL and was modified
# slightly to suit our needs:
# https://stackoverflow.com/a/8313042/1718477
def override(interface_class):
    """A decorator that checks and documents an overridden method.

    This function makes it obvious that a test is overriding a test in
    a base class. It also makes sure that the method actually exists in
    the base class.

    Example usage:

    >>> class A():
    ...     def foo(self):
    ...         pass
    ...
    >>> class B(A):
    ...     @override(A)
    ...     def foo(self):
    ...         pass
    """
    def overrider(method):
        if method.__name__ not in dir(interface_class):
            raise AssertionError(
                "{0} does not override a method in {1}".format(
                    method.__name__, interface_class.__name__))
        return method
    return overrider


# NOTE: I guess this pattern of defining test methods in a base class
# isn't directly supported by the unittest framework out of the box.
# For example, see:
# https://docs.python.org/2/library/unittest.html\
#   #unittest.TestLoader.loadTestsFromModule
#
# Instead, we use the suggestion given in this stackoverflow thread:
# http://stackoverflow.com/a/4566992/1718477
#
# That is, our abstract base class (InterfaceTestCase) inherits from
# object rather than CplexTestCase or unittest.TestCase, and we use
# multiple inheritance in the concrete class.  This seems like a
# reasonable compromise to get the behavior we want (primarily, to have
# less code duplication).
#
# WARNING: As a result, we will get errors if we run this module through
# pylint.

class InterfaceTestCase():
    """Mostly generic tests for Python API interfaces.

    These tests were originally created for the Annotation API, but it
    became apparent that they could be shared with others (e.g., the PWL
    API).  Methods like get_interface will need to be overridden.
    """

    # With test_encoding set to True, we test with some interesting
    # names. It's a good idea to test with test_endocing set to both
    # True and False.
    test_encoding = False

    def get_interface(self, cpx):
        """Return handle to an interface class.

        For example, the LongAnnotationInterface is access via
        Cplex.long_annotations.
        """
        raise NotImplementedError

    def getAsciiNames(self):
        """Return a list of names that can be used in `doSetUp`.

        Use ASCII characters to keep it simple.
        """
        return ["foo", "bang", "bar", "bat"]

    def getLatin1Names(self):
        """Return a list of names that can be used in `doSetUp`.

        Use some "extended" ASCII characters to make it interesting.
        """
        return ["motörhead", "Ørsted", "Gauß", "Nuñoz"]

    def getTestNames(self, cpx):
        if self.test_encoding:
            names = self.getLatin1Names()
        else:
            names = self.getAsciiNames()
        return names

    def doSetUp(self, cpx):
        """Generic test setup for the interface.

        Returns a tuple containing two lists: a list of names and a list
        of indices for newly created items.
        """
        raise NotImplementedError

    def addOne(self, cpx, name):
        """Should add one item with the given name.

        name can be None.

        If any supporting variables, etc., need to be added here, try to
        do it without adding names to the model.

        Returns the added index.
        """
        raise NotImplementedError

    def defaultName(self):
        """The default name root used for autogenerated names.

        For example, "x" for variables, "c" for constraints.
        """
        raise NotImplementedError

    @staticmethod
    def getnumitems(src, num):
        """Given a source list, return a list of size num."""
        srclen = len(src)
        if srclen == 1:
            return src * num
        else:
            return [src[i % srclen] for i in range(num)]

    def testEmpty(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            self.assertEqual(iface.get_num(), 0)

    def testAddOne(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            name = self.getTestNames(cpx)[0]
            idx = self.addOne(cpx, name=name)
            actual = iface.get_names(idx)
            self.assertEqual(actual, name)
            self.assertEqual(iface.get_num(), 1)

    def testAddOneNoNames(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            idx = self.addOne(cpx, name=None)
            self.assertEqual(iface.get_num(), 1)

    def testAddOneNone(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                idx = self.addOne(cpx, name=None)
                iface.get_names(idx)
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2], error_codes.CPXERR_NO_NAMES)

    def testAddOneEmptyString(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            idx = self.addOne(cpx, name="")
            actual = iface.get_names(idx)
            self.assertEqual(actual,
                             "{0}{1}".format(self.defaultName(), idx + 1))

    def testDeleteEmpty(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            # Expecting this to be a no-op (no exception thrown)
            iface.delete()

    def testDeleteByIndex(self):
        with self._newCplex() as cpx:
            _, indices = self.doSetUp(cpx)
            iface = self.get_interface(cpx)
            num = iface.get_num()
            self.assertGreater(num, 1)
            while num > 0:
                iface.delete(indices.pop())
                num -= 1
                self.assertEqual(iface.get_num(), num)
            self.assertEqual(iface.get_num(), 0)

    def testDeleteByName(self):
        with self._newCplex() as cpx:
            names, _ = self.doSetUp(cpx)
            iface = self.get_interface(cpx)
            num = iface.get_num()
            self.assertGreater(num, 1)
            while num > 0:
                iface.delete(names.pop())
                num -= 1
                self.assertEqual(iface.get_num(), num)
            self.assertEqual(iface.get_num(), 0)

    def testDeleteAll(self):
        with self._newCplex() as cpx:
            self.doSetUp(cpx)
            iface = self.get_interface(cpx)
            self.assertGreater(iface.get_num(), 1)
            iface.delete()
            self.assertEqual(iface.get_num(), 0)

    def testDeleteRangeByIndex(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            _, indices = self.doSetUp(cpx)
            self.assertGreater(iface.get_num(), 1)
            iface.delete(indices[0], indices[-1])
            self.assertEqual(iface.get_num(), 0)

    def testDeleteRangeByName(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            names, _ = self.doSetUp(cpx)
            self.assertTrue(iface.get_num() > 1)
            iface.delete(names[0], names[-1])
            self.assertEqual(iface.get_num(), 0)

    def testDeleteIndexSequence(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            _, indices = self.doSetUp(cpx)
            self.assertGreater(iface.get_num(), 1)
            iface.delete(indices)
            self.assertEqual(iface.get_num(), 0)

    def testDeleteNameSequence(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            names, _ = self.doSetUp(cpx)
            self.assertGreater(iface.get_num(), 1)
            iface.delete(names)
            self.assertEqual(iface.get_num(), 0)

    def testDeleteBadName(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                self.doSetUp(cpx)
                iface.delete("bogus")
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2], error_codes.CPXERR_NAME_NOT_FOUND)

    @unittest.skip("FIXME: See _aux_functions.py:delete_set")
    def testDeleteRangeByIndexBad(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                _, indices = self.doSetUp(cpx)
                self.assertGreater(iface.get_num(), 1)
                # We reverse the arguments, expecting this to cause an
                # error (b/c begin > end).
                begin = indices[0]
                end = indices[-1]
                self.assertGreater(end, begin)
                iface.delete(end, begin)
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2], error_codes.CPXERR_INDEX_RANGE)

    def testDeleteBadIndex(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                _, indices = self.doSetUp(cpx)
                iface.delete(max(indices) + 1)
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2], error_codes.CPXERR_INDEX_RANGE)

    def testDeleteIntermixed(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            for i in range(10):
                self.addOne(cpx, name=str(i))
            self.assertEqual(
                ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
                iface.get_names())
            iface.delete(8)
            self.assertEqual(
                ['0', '1', '2', '3', '4', '5', '6', '7', '9'],
                iface.get_names())
            iface.delete('1', 3)
            self.assertEqual(
                ['0', '4', '5', '6', '7', '9'],
                iface.get_names())
            iface.delete([2, '0', 5])
            self.assertEqual(
                ['4', '6', '7'],
                iface.get_names())
            iface.delete()
            self.assertEqual([], iface.get_names())

    def testDeleteWrongNumberOfArgs(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                iface.delete(0, 1, 2)
                self.fail()
        except WrongNumberOfArgumentsError:
            pass

    def testGetIndicesNoNames(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                idx = iface.get_indices("bogus")
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2], error_codes.CPXERR_NAME_NOT_FOUND)

    def testGetIndicesBad(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                self.doSetUp(cpx)
                idx = iface.get_indices("bogus")
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2], error_codes.CPXERR_NAME_NOT_FOUND)

    def testGetName(self):
        with self._newCplex() as cpx:
            expected_names, indices = self.doSetUp(cpx)
            iface = self.get_interface(cpx)
            actual_names = [iface.get_names(idx) for idx in indices]
            self.assertEqual(expected_names, actual_names)

    def testGetNameNoNames(self):
        try:
            with self._newCplex() as cpx:
                _, indices = self.doSetUp(cpx)
                iface = self.get_interface(cpx)
                cpx.advanced.delete_names()
                iface.get_names(indices[0])
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2],
                             error_codes.CPXERR_NO_NAMES)

    def testGetNameAll(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            expected_names, indices = self.doSetUp(cpx)
            actual_names = iface.get_names()
            self.assertEqual(actual_names, expected_names)

    def testGetNameAllNoNames(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                self.doSetUp(cpx)
                cpx.advanced.delete_names()
                iface.get_names()
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2],
                             error_codes.CPXERR_NO_NAMES)

    def testGetNameRange(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            expected_names, indices = self.doSetUp(cpx)
            actual_names = iface.get_names(indices[0], indices[-1])
            self.assertEqual(actual_names, expected_names)


    def testGetNameEmptyRange(self):
        with self._newCplex() as cpx:
            iface = self.get_interface(cpx)
            expected_names, indices = self.doSetUp(cpx)
            actual_names = iface.get_names(0, -1)
            self.assertEqual(actual_names, [])

    def testGetNameRangeNoNames(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                _, indices = self.doSetUp(cpx)
                cpx.advanced.delete_names()
                iface.get_names(indices[0], indices[-1])
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2],
                             error_codes.CPXERR_NO_NAMES)

    def testGetNameBad(self):
        try:
            with self._newCplex() as cpx:
                iface = self.get_interface(cpx)
                _, indices = self.doSetUp(cpx)
                name = iface.get_names(max(indices) + 1)
                self.fail()
        except CplexSolverError as cse:
            self.assertEqual(cse.args[2],
                             error_codes.CPXERR_INDEX_RANGE)

    def testWithMultipleInstances(self):
        """RTC-33155"""
        cpx1 = self._newCplex()
        iface1 = self.get_interface(cpx1)
        self.addOne(cpx1, name="foo")
        self.assertEqual(iface1.get_num(), 1)
        cpx2 = self._newCplex()
        iface2 = self.get_interface(cpx2)
        self.assertEqual(iface2.get_num(), 0)
        self.assertEqual(iface1.get_num(), 1)
